# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='contact_person',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='contact_position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 10, 57, 5, 385000)),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='remarks',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='telephone1',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='telephone2',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
