# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0004_auto_20170106_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 10, 29, 48, 803000)),
        ),
    ]
