# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:29
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankbranch', '0006_auto_20170110_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_bankbranch_id', to='bank.Bank', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 29, 54, 260000)),
        ),
    ]
