# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptype',
            options={'ordering': ['-pk'], 'permissions': (('view_aptype', 'Can view aptype'),)},
        ),
        migrations.AlterField(
            model_name='aptype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 6, 18, 834000)),
        ),
    ]
