# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvtype',
            options={'ordering': ['-pk'], 'permissions': (('view_cvtype', 'Can view cvtype'),)},
        ),
        migrations.AlterField(
            model_name='cvtype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 6, 5, 301000)),
        ),
    ]
