# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistype',
            old_name='lastmisno',
            new_name='lastno',
        ),
        migrations.RenameField(
            model_name='mistype',
            old_name='misreason',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='mistype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 16, 34, 35, 5000)),
        ),
    ]
