# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 13, 10, 44, 2, 771000)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='multiplestatus',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
