# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170117_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creditterm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='creditterm_id', to='creditterm.Creditterm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 23, 13, 10, 23, 701000)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payterms',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telno1',
            field=models.CharField(max_length=20),
        ),
    ]
