# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 10, 26, 49, 294000)),
        ),
    ]
