# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_auto_20170109_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='industry',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 10, 30, 32, 660000)),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
