# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_auto_20170109_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-pk'], 'permissions': (('view_industry', 'Can view industry'),)},
        ),
        migrations.AlterField(
            model_name='industry',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 5, 23, 922000)),
        ),
    ]
