# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindofexpense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofexpense',
            options={'ordering': ['-pk'], 'permissions': (('view_kindofexpense', 'Can view kindofexpense'),)},
        ),
        migrations.AlterField(
            model_name='kindofexpense',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 4, 2, 705000)),
        ),
    ]
