# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindofexpense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindofexpense',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 15, 0, 16, 256000)),
        ),
        migrations.AlterField(
            model_name='kindofexpense',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1),
        ),
    ]
