# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 16, 36, 26, 828000)),
        ),
    ]
