# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 02:57
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_auto_20170104_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='mainunit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mainunit_id', to='mainunit.Mainunit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 10, 57, 54, 386000)),
        ),
    ]
