# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20170109_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-pk'], 'permissions': (('view_currency', 'Can view currency'),)},
        ),
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 4, 53, 583000)),
        ),
    ]
