# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20170111_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 14, 19, 37, 191000)),
        ),
    ]
