# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtax', '0002_auto_20170118_1726'),
        ('wtax', '0002_auto_20170110_1703'),
    ]

    operations = [
    ]
