# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='beg_code',
            field=models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 9, 50, 44, 825000)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='run_code',
            field=models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1, null=True),
        ),
    ]
