# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 13, 20, 11, 640000)),
        ),
    ]
