# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_auto_20170109_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-pk'], 'permissions': (('view_bankaccount', 'Can view bankaccount'),)},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 6, 30, 491000)),
        ),
    ]
