# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_auto_20170110_1706'),
        ('bankaccount', '0003_auto_20170112_1013'),
    ]

    operations = [
    ]
