# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0004_auto_20170118_1728'),
        ('bankaccount', '0006_auto_20170113_1042'),
    ]

    operations = [
    ]
