# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-16 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 15, 36, 44, 920591)),
        ),
    ]
