# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20170104_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-pk'], 'permissions': (('view_bank', 'Can view bank'),)},
        ),
        migrations.AlterField(
            model_name='bank',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 4, 49, 566000)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1),
        ),
    ]
