# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170109_1320'),
        ('bank', '0004_auto_20170110_1704'),
    ]

    operations = [
    ]
