# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 01:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20170111_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 9, 45, 56, 239000)),
        ),
    ]
