# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0002_auto_20170104_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvattype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 17, 11, 38, 370000)),
        ),
    ]
