# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputvattype', '0003_auto_20170104_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvattype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 17, 20, 45, 352000)),
        ),
    ]
