# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 02:18
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbudget',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 10, 18, 33, 46000)),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1980)]),
        ),
    ]
