# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-20 02:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbudget', '0002_auto_20170119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbudget',
            name='mapr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='maug',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mdec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mfeb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mjan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mjul',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mjun',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mmar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mmay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='mnov',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='moct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 20, 10, 2, 46, 935000)),
        ),
        migrations.AlterField(
            model_name='productbudget',
            name='msep',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
