# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customertype', '0002_auto_20170112_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 13, 10, 42, 45, 378000)),
        ),
    ]
