# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0002_auto_20170110_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['-pk'], 'permissions': (('view_chartofaccount', 'Can view chartofaccount'),)},
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 13, 46, 4, 322000)),
        ),
    ]
