# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0006_auto_20170111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 14, 31, 49, 418000)),
        ),
    ]
