# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 07:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0007_auto_20170111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='kindofexpense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kindofexpense_id', to='kindofexpense.Kindofexpense', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 15, 50, 7, 2000)),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='sub',
            field=models.CharField(default='00', max_length=6, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='typeofexpense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeofexpense_id', to='typeofexpense.Typeofexpense', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
