# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 01:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0008_auto_20170111_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='kindofexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kindofexpense_id', to='kindofexpense.Kindofexpense', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='mainunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainunit_chartofaccount_id', to='mainunit.Mainunit', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 12, 9, 54, 46, 338000)),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.Product', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='sub',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='typeofexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeofexpense_id', to='typeofexpense.Typeofexpense', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
