# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0028_auto_20170118_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 17, 23, 56, 898000)),
        ),
    ]
