# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0031_auto_20170118_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 7, 50, 52, 392000)),
        ),
    ]
