# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0032_auto_20170119_0750'),
        ('chartofaccount', '0026_auto_20170119_0959'),
    ]

    operations = [
    ]
