# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='departmentname',
        ),
        migrations.AlterField(
            model_name='department',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 23, 13, 43, 42, 468000)),
        ),
    ]
