# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 16, 11, 41, 900000)),
        ),
    ]
