# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 01:29
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('module', '0002_auto_20170110_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='django_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='django_content_type_id', to='contenttypes.ContentType', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 9, 29, 57, 523000)),
        ),
    ]
