# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_auto_20170111_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='mainmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainmodule_id', to='mainmodule.Mainmodule'),
        ),
        migrations.AlterField(
            model_name='module',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 13, 45, 0, 714000)),
        ),
    ]
