# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20170119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 14, 38, 47, 424000)),
        ),
    ]
