# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20170119_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 16, 34, 0, 51000)),
        ),
    ]
