# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 09:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputvattype', '0006_auto_20170104_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inputvat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('inputvatchartofaccount_id', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 17, 27, 34, 524000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvattype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_inputvattype', to='inputvattype.Inputvattype')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'inputvat',
            },
        ),
    ]
