# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputvat', '0002_auto_20170104_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvat',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 17, 34, 8, 582000)),
        ),
    ]
