# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-17 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputvat', '0003_auto_20170116_1527'),
        ('inputvat', '0002_auto_20170110_1703'),
    ]

    operations = [
    ]
