# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 01:14
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataxcode',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 9, 14, 45, 483000)),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='rate',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
