# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 01:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0002_auto_20170104_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataxcode',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='enterby',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_enter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='isdeleted',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='modifyby',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 9, 22, 58, 403000)),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='rate',
            field=models.IntegerField(default=0, editable=False, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', editable=False, max_length=1),
        ),
    ]
