# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 01:38
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0005_auto_20170104_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataxcode',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 9, 38, 48, 454000)),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='rate',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1),
        ),
    ]
