# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataxcode', '0007_auto_20170104_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataxcode',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 11, 15, 40, 562000)),
        ),
        migrations.AlterField(
            model_name='ataxcode',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
