# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounttype', '0003_auto_20170109_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccounttype',
            options={'ordering': ['-pk'], 'permissions': (('view_bankaccounttype', 'Can view bankaccounttype'),)},
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 17, 5, 49, 32000)),
        ),
    ]
