# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounttype', '0004_auto_20170110_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 13, 27, 39, 321000)),
        ),
    ]
