# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounttype', '0007_auto_20170111_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 14, 15, 40, 253000)),
        ),
    ]
