# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cmsgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmsgroup_id', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 14, 45, 43, 803957)),
        ),
    ]
