# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 01:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk'], 'permissions': (('view_product', 'Can view product'),)},
        ),
        migrations.AlterField(
            model_name='product',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 9, 59, 42, 712000)),
        ),
    ]
