# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-05 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170105_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cmsgroup',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmsgroup_id', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 9, 42, 10, 988197)),
        ),
    ]
