# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-05 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170105_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cmsgroup',
            new_name='cmsgroup_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 9, 51, 55, 865587)),
        ),
    ]
