# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0002_auto_20170104_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='effectivedatefrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vat',
            name='effectivedateto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vat',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 13, 20, 59, 484000)),
        ),
    ]
