# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-20 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsupplier_supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsupplier_supplier',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 20, 10, 39, 33, 111000)),
        ),
        migrations.AlterUniqueTogether(
            name='mainsupplier_supplier',
            unique_together=set([('mainsupplier', 'supplier')]),
        ),
    ]
